### PR TITLE
allow to work without debug library

### PR DESCRIPTION
**Pull request by fperrad**
the use of [debug](https://www.lua.org/manual/5.4/manual.html#6.10) library could be not safe, or at least no recommended.

I want run code with a Lua interpreter compiled without this library `debug`.

### CODE REVIEW

**Comment by Tieske** [comment]
should we run the test suite twice, 2nd time with the debug lib disabled? eg. passing `-e "_G.debug = nil"` to the Lua interpreter?

**Comment by fperrad** [comment]
yes, `LUA_PATH="../src/?.lua;$LUA_PATH" lua -e "_G.debug = nil" test.lua` will work

**Comment by fperrad** [comment]
another way is `LUA_PATH="../src/?.lua;$LUA_PATH" LUA_INIT="_G.debug = nil" lua test.lua`

and few tests in `tests/generic.lua` must be modified (`tests.logPatterns` & `tests.format_error_stacktrace`)

**Review by Tieske — APPROVED** [review]

**Comment by Tieske** [comment]
@fperrad do you have more up your sleeve, or can I push another release with this fix?

**Comment by fperrad** [comment]
@Tieske nothing more, so you could push a release

**Comment by Tieske** [comment]
done in 1.8.2

**Pull request merged**
