### PR TITLE
Introduce CI testing via GitHub actions

### PR DESCRIPTION
**Pull request by ynezz**
Also fixes tests on Lua 5.1.

### CODE REVIEW

**Comment by ynezz** [comment]
Result https://github.com/ynezz/lualogging/actions/runs/249955283

**Comment by Tieske** [comment]
Does GH actions also support Windows? We need to test that too

**Comment by ynezz** [comment]
> Does GH actions also support Windows? We need to test that too

From https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on


Virtual environment | YAML workflow label
-- | --
Windows Server 2019 | windows-latest or windows-2019
Ubuntu 20.04 | ubuntu-20.04
Ubuntu 18.04 | ubuntu-latest or ubuntu-18.04
Ubuntu 16.04 | ubuntu-16.04
macOS Catalina 10.15 | macos-latest or macos-10.15

**Comment by Tieske** [comment]
@ynezz just merged it, but clicking the badge at the top of the readme doesn't work, any ideas?

**Comment by ynezz** [comment]
> but clicking the badge at the top of the readme doesn't work, any ideas?

A status badge **shows** whether a workflow is currently failing or passing. I'm not sure if one can do more with Markdown.

**Comment by Tieske** [comment]
typically with Travic-CI, clicking it would take you to the test run

this one is like:

    build status

a Travis one would be

    [Build Status](https://travis-ci.com/Tieske/lua-resty-ljsonschema)

**Comment by Tieske** [comment]
so this should be created... but what is the dynamic link?

    [build status](https://github.com/lunarmodules/lualogging/actions?query=workflow%3Atest)

**Comment by Tieske** [comment]
Google cam up empty, only some folks looking for the same links that seem not to exist (yet). So for now I used the above one as the closest match.

**Comment by ynezz** [comment]
Yep, I came with the same solution https://github.com/ynezz/lualogging/commit/fdb6419cadfc2a217d6f99cd4afe436c02a6f607

**Pull request merged**
